/*
------------------------------------------------------------------------------------------------------------------
"post.js" contains the functionality that is required to generate a page based on user choices with the help of 
cookies or localStorage(whichever is applicable)
Author-Balaji Jagadeesan
------------------------------------------------------------------------------------------------------------------
*/
var hitcount; //To store the number of times a user visited the website
var user; //To store the name of the user
var choice; //To store the option generated by the user
var comment; //To store the comment given by the user
/*
--------------------------------------------------------
The following contains the AJAX code to retrieve the JSON 
data from the file "data.json" 
post(data) is invoked to retrieve the stored data
--------------------------------------------------------
*/
var http = new XMLHttpRequest();
var url = "data.json";
//console.log(url)
http.onreadystatechange = function () {
	if (this.readyState == 4 && this.status == 200) {
		var myArr = JSON.parse(this.responseText);
		post(myArr);
	}
};
http.open("GET", url, true);
http.send();
/*
-----------------------------------------------------------
The following function is used to retrieve the choice and 
user details from localStorage(if available) or from cookies.

gendata() is invoked to output the data retrieved 
-----------------------------------------------------------
*/
function post(array) {
	if (localStorage.getItem("options") != null) {
		choice = JSON.parse(localStorage.getItem("options"));
		var name = JSON.parse(localStorage.getItem("name"));
		var hits = JSON.parse(localStorage.getItem("hits"));
		var com = JSON.parse(localStorage.getItem("comment"));
		for (i = 0; i < name.length; i++) {
			if (name[i] == JSON.parse(localStorage.getItem("temp"))) {
				hitcount = parseInt(hits[i]);
				user = name[i];
				comment = com[i];
			}
			console.log(hitcount);
			console.log(user);
		};
	}
	else if (GetCookie("options") != null) {
		choice = JSON.parse(GetCookie("options"));
		var name = JSON.parse(GetCookie("name"));
		var hits = JSON.parse(GetCookie("hits"));
		for (i = 0; i < name.length; i++) {
			if (name == GetCookie("temp")) {
				hitcount = parseInt(hits[i]);
				user = name[i];
			}
		}
	}
	gendata(array, choice);
}
/*
-----------------------------------------------------------
The following function outputs all the retrieved data 
to the html page using DOM elements
It also creates images corresponding to the user choice.
------------------------------------------------------------
*/
function gendata(array, choice) {
	//console.log(hitcount);
	//console.log(user);
	//console.log(choice);
	if (hitcount == 1) {
		hitcount = hitcount + 'st';
	}
	else if (hitcount == 2) {
		hitcount = hitcount + "nd";
	}
	else if (hitcount == 3) {
		hitcount = hitcount + "rd";
	}
	else {
		hitcount = hitcount + "th";
	}
	var myDiv = document.getElementById("choice");
	var div1 = document.createElement("div")
	div1.setAttribute("id", "mydiv")
	div1.setAttribute("class", "cards")
	var para = document.createElement("p");
	var node = document.createTextNode("Welcome " + user + ". This is your '" + hitcount + " time' visting our website.You require '" + choice[0] + "' computer of subclass '" + choice[1] + "'. The model you have chosen is '" + choice[2] + "' .Your comment on our product is '" + comment + "'");
	para.appendChild(node);
	div1.appendChild(para);
	myDiv.appendChild(div1);
	for (i = 0; i < choice.length; i++) {
		var myDiv = document.getElementById("imagels");
		var pic = document.createElement("img");
		pic.setAttribute("id", "pic");
		pic.setAttribute("alt", "picture");
		//console.log(array[choice[i]]["image"]);
		pic.setAttribute("src", array[choice[i]]["image"]);
		myDiv.appendChild(pic);
	}
}